from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from alg1 import first_algos
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton, 
                             QToolTip, QMessageBox, QLabel)
from alg2 import Second
from fact import First

def raschot(dct):
    fst = First(dct['r_s'], dct['p_s'], dct['d_s'])
    scd = Second(dct['r_s'], dct['p_s'], dct['d_s'])
    s = ''
    if dct['algos'][0]:
        scd.algos2()
        s+='Результат алгоритма максимального времени смещения: ' + f'с прерыванием: {scd.best}  {scd.ans1}   и без прерывания{scd.best2}  {scd.ans2}' + '\n'
    if dct['algos'][2]:
        rez = fst.first_algos()
        s+='Результат алгоритма полного перебора:' + f'{fst.best}  {rez}' + '\n'
    if dct['algos'][1]:
        pass
    return s

class Ui_MainWindow1(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 598)
        MainWindow.setStyleSheet("background-color: #FAEEDD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 60, 791, 441))
        self.textBrowser.setStyleSheet("background-color:\"white\";\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 530, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Результаты работы алгоритмов:"))
        self.pushButton.setText(_translate("MainWindow", "Сравнить результаты"))


class Ui_MainWindow2(QMainWindow):
    def get_data(self):
        data = dict({})
        data['n'] = int(self.textEdit.toPlainText())
        data['r_s'] = list(map( int, self.textEdit_2.toPlainText().split()))
        data['p_s'] = list(map( int, self.textEdit_3.toPlainText().split()))
        data['d_s'] = list(map( int, self.textEdit_4.toPlainText().split()))
        data['w_s'] = list(map( int, self.textEdit_5.toPlainText().split()))
        data['func'] = self.comboBox.currentText()
        data['algos'] = [self.checkBox.isChecked(), self.checkBox_2.isChecked(), self.checkBox_3.isChecked()]
        return data

    def is_pushed2(self):
        s = raschot(self.get_data())
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.textBrowser.setText(s)

        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 578)
        MainWindow.setStyleSheet("background-color: #FAEEDD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(560, 340, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(350, 290, 151, 31))
        self.textEdit_4.setStyleSheet("background-color:\"white\";")
        self.textEdit_4.setObjectName("textEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 420, 151, 41))
        self.comboBox.setStyleSheet("background-color:\"white\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(350, 220, 151, 31))
        self.textEdit_3.setStyleSheet("background-color:\"white\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(560, 140, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 420, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(560, 230, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 150, 151, 31))
        self.textEdit_2.setStyleSheet("background-color:\"white\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(570, 60, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 350, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(350, 360, 151, 31))
        self.textEdit_5.setStyleSheet("background-color:\"white\";")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 80, 151, 31))
        self.textEdit.setStyleSheet("background-color:\"white\";")
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.is_pushed2())
        self.pushButton_2.setGeometry(QtCore.QRect(800, 510, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 510, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_3.setText(_translate("MainWindow", "Алгоритм перебора (n!)"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.comboBox.setItemText(0, _translate("MainWindow", "F(п) = max {0; tj-dj}"))
        self.comboBox.setItemText(1, _translate("MainWindow", "F(п) = max {tj-dj}"))
        self.comboBox.setItemText(2, _translate("MainWindow", "F(п) = max (tj-pj)"))
        self.comboBox.setItemText(3, _translate("MainWindow", "F(п) = max (tj+pj)"))
        self.comboBox.setItemText(4, _translate("MainWindow", "F(п) = max WjLj"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F(п) = max Wjzj"))
        self.comboBox.setItemText(6, _translate("MainWindow", "F(п) = Wjtj"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.label.setText(_translate("MainWindow", "Размерность:"))
        self.checkBox.setText(_translate("MainWindow", "Минимизация максимального времени смещения "))
        self.label_6.setText(_translate("MainWindow", "Функция штрафа:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Введите через пробел p<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.checkBox_2.setText(_translate("MainWindow", "Минимизация максимального штрафа \n"
" с произвольными неубывающими \n"
" штрафными функциями "))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "от 0 до n"))
        self.label_8.setText(_translate("MainWindow", "Выберите необходимые методы решения:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Введите через пробел W<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Уточните данные:"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Введите через пробел d<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Введите через пробел r<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Следующий шаг "))
        self.pushButton_3.setText(_translate("MainWindow", "Выбрать случайную функицю штрафа"))


class Ui_MainWindow(QMainWindow):
    def get_data(self):
        data = dict({})
        data['n'] = int(self.textEdit.toPlainText())
        data['r_s'] = list(map( int, self.textEdit_2.toPlainText().split()))
        data['p_s'] = list(map( int, self.textEdit_3.toPlainText().split()))
        data['d_s'] = list(map( int, self.textEdit_4.toPlainText().split()))
        data['w_s'] = list(map( int, self.textEdit_5.toPlainText().split()))
        data['func'] = self.comboBox.currentText()
        data['algos'] = [self.checkBox.isChecked(), self.checkBox_2.isChecked(), self.checkBox_3.isChecked()]
        return data


    def is_pushed1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()


    def is_pushed2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.textBrowser.setText("Результат:")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 612)
        MainWindow.setStyleSheet("background-color: #FAEEDD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 410, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(330, 60, 151, 31))
        self.textEdit.setStyleSheet("background-color:\"white\";")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(330, 120, 151, 31))
        self.textEdit_2.setStyleSheet("background-color:\"white\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(330, 180, 151, 31))
        self.textEdit_3.setStyleSheet("background-color:\"white\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(330, 240, 151, 31))
        self.textEdit_4.setStyleSheet("background-color:\"white\";")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(330, 300, 151, 31))
        self.textEdit_5.setStyleSheet("background-color:\"white\";")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(330, 420, 151, 31))
        self.textEdit_7.setStyleSheet("background-color:\"white\";")
        self.textEdit_7.setObjectName("textEdit_7")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 350, 151, 41))
        self.comboBox.setStyleSheet("background-color:\"white\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 480, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.is_pushed2())
        self.pushButton_2.setGeometry(QtCore.QRect(840, 540, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 540, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(550, 170, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(550, 250, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(550, 350, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 90, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.is_pushed1())
        self.pushButton_4.setGeometry(QtCore.QRect(370, 480, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: #FFE4C4;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Размерность:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Диапазон изменения r<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Диапазон изменения p<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Диапазон изменения d<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Диапазон изменения W<span style=\" vertical-align:sub;\">j</span>:</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Функция штрафа:"))
        self.label_7.setText(_translate("MainWindow", "Количество экспериментов:"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "от 0 до n"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.textEdit_7.setPlaceholderText(_translate("MainWindow", "от 1 до n"))
        self.comboBox.setItemText(0, _translate("MainWindow", "F(п) = max {0; tj-dj}"))
        self.comboBox.setItemText(1, _translate("MainWindow", "F(п) = max {tj-dj}"))
        self.comboBox.setItemText(2, _translate("MainWindow", "F(п) = max (tj-pj)"))
        self.comboBox.setItemText(3, _translate("MainWindow", "F(п) = max (tj+pj)"))
        self.comboBox.setItemText(4, _translate("MainWindow", "F(п) = max WjLj"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F(п) = max Wjzj"))
        self.comboBox.setItemText(6, _translate("MainWindow", "F(п) = Wjtj"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать данные за меня "))
        self.pushButton_2.setText(_translate("MainWindow", "Следующий шаг "))
        self.pushButton_3.setText(_translate("MainWindow", "Выбрать случайную функицю штрафа"))
        self.checkBox.setText(_translate("MainWindow", "Минимизация максимального времени смещения "))
        self.checkBox_2.setText(_translate("MainWindow", "Минимизация максимального штрафа \n"
" с произвольными неубывающими \n"
" штрафными функциями "))
        self.checkBox_3.setText(_translate("MainWindow", "Алгоритм перебора (n!)"))
        self.label_8.setText(_translate("MainWindow", "Выберите необходимые методы решения:"))
        self.label_9.setText(_translate("MainWindow", "Уточните данные:"))
        self.pushButton_4.setText(_translate("MainWindow", "Ввести данные вручную"))

    

        

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())   